name: Build

on:
    push:
      branches:
        - master

jobs:
  build_Linux:
    name: Linux
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 11
    - name: Change wrapper permissions
      run: chmod +x ./gradlew
    - name: Turn off the gradle Daemon
      shell: bash
      run: ./gradle --stop
    - name: Cleanup the Gradle cache
      shell: bash
      run: |
        rm -f ~/.gradle/caches/modules-2/modules-2.lock
        rm -f ~/.gradle/caches/modules-2/gc.properties
    - name: Clean Project
      run: ./gradlew clean
    - name: Generate Native Project
      run: ./gradlew generateNativeProject
    - name: Build Project
      run: ./gradlew build
    - name: Upload to repository
      run: ./gradlew publish
      env:
        USER: ${{ secrets.USER }}
        PASSWORD: ${{ secrets.PASSWORD }}